import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { Navbar } from "@/components/organisms/Navbar";

// ✅ STATIC EXPORT: genera le versioni /en e /it
export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "it" }];
}

// ✅ Google Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ✅ SEO
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ✅ ROOT LAYOUT MULTILINGUA
export default async function RootLayout(props: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const language = props.params.locale || 'en'; // ✅ corretto

  let messages;
  try {
    messages = (await import(`@/messages/${language}.json`)).default;
  } catch {
    notFound();
  }

  return (
    <html lang={language} className="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider locale={language} messages={messages}>
          <Navbar />
          {props.children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
